#!/usr/bin/env python
from fusil.application import Application
from sys import exit

def main():
    fusil = Application()
    exitcode = fusil.main()
    fusil.exit()
    del fusil
    exit(exitcode)

if __name__ == "__main__":
    main()

